[package]
name = "kafka-example"
version = "0.1.2"
edition = "2021"

[dependencies]
kincir = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }